__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

так как умножать мы можем матрицы в которых количество строк одной матрицы равно количеству столбцов второй матрицы, то:

    а) нельзя перемножить без транспонирования одной матрицы;
    
    б) можно перемножить и мы получим матрицу 2 х 3;
    
    в) получим квадратную матрицу 8х8;
    
    г) так же квадратная 4х4.

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [38]:
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

A_plus_B = np.array([[A[0][0] + B[0][0], A[0][1] + B[0][1]], [A[1][0] + B[1][0], A[1][1] + B[1][1]]])
print(AB)


[[ 5 -3]
 [ 3  5]]


In [40]:
A+B

array([[ 5, -3],
       [ 3,  5]])

In [27]:
A_on_B = np.array([[A[0][0]*B[0][0]+A[0][1]*B[1][0], A[0][0]*B[0][1]+ A[0][1]*B[1][1]], [A[1][0]*B[0][0] + A[1][1]*B[1][0], A[1][0]*B[0][1]+A[1][1]*B[1][1]]])
print(A_on_B)

[[  4 -11]
 [ 12  -3]]


In [41]:
np.dot(A, B)

array([[  4, -11],
       [ 12,  -3]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [42]:
A = np.array([[1, 7], [3, (-6)]])
B = np.array([[0, 5], [2, (-1)]])
C = np.array([[2, (-4)], [1, 1]])

In [43]:
three_A = np.dot(3, A)
two_B = np.dot(2, B)
four_C = np.dot(4, C)

In [44]:
three_A_minus_two_B_plus_four_C = np.array([[three_A[0][0]-two_B[0][0]+four_C[0][0], three_A[0][1]-two_B[0][1]+four_C[0][1]],[three_A[1][0]-two_B[1][0]+four_C[1][0], three_A[1][1]-two_B[1][1]+four_C[1][1]]])
print(three_A_minus_two_B_plus_four_C)



[[ 11  -5]
 [  9 -12]]


In [45]:
three_A-two_B+four_C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [56]:
A = np.array([[4,1],[5, -2], [2, 3]])
At = np.array([[4, 5, 2], [1, -2, 3]])
At

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [57]:
A_At = np.array([[(4*4+1*1), (4*5+1*(-2)), (4*2+1*3)], [(5*4+(-2)*1), (5*5+(-2)*(-2)), (5*2+(-2)*3)], [(2*4+3*1), (2*5+3*(-2)), (2*2 +3*3)]])
A_At

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [58]:
At_A = np.array([[(4*4+5*5+2*2), (4*1+5*(-2)+2*3)],[(1*4+(-2)*5+3*2), (1*1+(-2)*(-2)+3*3)]])
print(At_A)

[[45  0]
 [ 0 14]]


In [59]:
At=np.transpose(A)
print(At)

[[ 4  5  2]
 [ 1 -2  3]]


In [60]:
np.dot(A, At)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [61]:
np.dot(At, A)

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [73]:
def matrix_dot(a, b):
    if len(a[0]) == len(b):
        m_dot = []
        for itm in a:
            i = 0
            while i < len(a[0]):
                m_dot.append(a[itm-1][i] * b[i][itm-1])      
            i +=1
        else:
            print("you cant do it beczuse different shapes")
        return m_dot
            

In [74]:
matrix_dot(A, At)


IndexError: index 3 is out of bounds for axis 0 with size 3

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

detA = sin(x)*sin(x) - (-cos(x))*cos(x) = 1

In [82]:
detB = 4*(5*9 - 1*0) -2*(0)+3*(0) 
print(dotB)

180


In [95]:
detV = 1*(5*9 - 6*8) + (-2)*(4*9 - 6*7) + 3*(4*8 - 5*7)
detV

0

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

In [102]:
det_a_square = 4*4
det_a_square

16

16 так как это частный случай кратных матриц

In [103]:
det_a_t = 4 
det_a_t

4

так как определители матрицы и транспонированной матрицы равны

In [104]:
det_two_a = 4*2
det_two_a

8

так как умножение матрицы приведет к умножению определителя. 

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$

вырожденная.

вычтем из второй строки первую помноженную на -2

$$\begin{pmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0\\ 
-3 & 7 & 13
\end{pmatrix}$$

посчитаем определитель

In [105]:
det = -2*(0*13 - 0*7)+(-7)*(0*13-0*(-3))+(-3)*(0*13-0*(-3))
det

0

при опредедителе равном нулю матрица является вырожденной.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

rank_a = 2 так как третья строка равна сумме первых двух

rank_b = 3 так как сумма первых двух равна третьей строке. 