1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [1]:
import numpy as np
import math
np.set_printoptions(precision=2, suppress=True)

In [2]:
A = np.array([[1,2,0], 
              [0,0,5],
              [3,-4,2],
              [1,6,5],
              [0,1,0],])

In [3]:
U, s, W = np.linalg.svd(A)
V = W.T

In [4]:
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [5]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [6]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [7]:
print(f'Матрица V.T:\n{V.T}')

Матрица V.T:
[[ 0.07  0.72  0.69]
 [-0.37  0.67 -0.65]
 [-0.93 -0.21  0.31]]


In [8]:
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]


In [9]:
two_a = D[0][0]
print(two_a)

8.824868854820442


In [11]:
two_b = math.sqrt(D[0][0]*D[0][0]+D[1][1]*D[1][1]+D[2][2]*D[2][2])
two_b

11.045361017187261